# Generated by Django 5.2.9 on 2025-12-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address_line', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phường/Xã')),
                ('district', models.CharField(max_length=255, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=255, verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Danh sách cửa hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreReservation',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID đặt hàng')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('status', models.CharField(max_length=20, verbose_name='Trạng thái')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm đặt hàng')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hết hạn')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Khách hàng')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Sản phẩm')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Cửa hàng nhận hàng',
                'verbose_name_plural': 'Danh sách của hàng nhận',
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('reserved_stock', models.IntegerField(default=0, verbose_name='Đã giữ (reserved)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mã sản phẩm')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Mã cửa hàng')),
            ],
            options={
                'verbose_name': 'Kho',
                'verbose_name_plural': 'Danh sách tồn kho cửa hàng',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
