# Generated by Django 5.2.9 on 2025-12-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_id'),
        ('stores', '0002_alter_storereservation_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('store', 'product')},
        ),
        migrations.RemoveField(
            model_name='storereservation',
            name='products',
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Mã cửa hàng'),
        ),
        migrations.AddField(
            model_name='storereservation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Cửa hàng'),
        ),
        migrations.RemoveField(
            model_name='storeinventory',
            name='products',
        ),
    ]
