# Generated by Django 5.2.9 on 2026-01-04 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Số sao')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('label', models.CharField(max_length=20, verbose_name='Cảm xúc')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Mã khách hàng')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mã sản phẩm')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Danh sách bình luận',
            },
        ),
    ]
