# Generated by Django 5.2.9 on 2026-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam_score',
            field=models.FloatField(default=0, verbose_name='Điểm spam'),
        ),
    ]
