# Generated by Django 5.2.9 on 2026-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_is_spam_comment_spam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cảm xúc'),
        ),
    ]
