# Generated by Django 5.2.8 on 2025-12-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Ảnh sản phẩm')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ảnh (SEO)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Đặt làm ảnh chính')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
