# Generated by Django 5.2.8 on 2025-12-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
