# Generated by Django 5.2.9 on 2025-12-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productattribute_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
