# Generated by Django 5.2.8 on 2025-12-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Hãng')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/', verbose_name='Ảnh chính')),
                ('warranty_month', models.IntegerField(default=12, verbose_name='Bảo hành (tháng)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
                'db_table': 'Product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
