# Generated by Django 5.2.9 on 2025-12-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='Mã chương trình'),
        ),
    ]
