# Generated by Django 5.2.9 on 2025-12-19 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPartner',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='Mã ĐVVC')),
                ('name', models.CharField(max_length=255, verbose_name='Tên đơn vị vận chuyển')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã code')),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Logo')),
                ('price', models.DecimalField(decimal_places=2, default=30000, max_digits=12, verbose_name='Giá cước')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Đơn vị vận chuyển',
                'verbose_name_plural': 'Danh sách đơn vị vận chuyển',
            },
        ),
        migrations.CreateModel(
            name='OrderShipping',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order', verbose_name='Mã đơn hag')),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã vận đơn')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Phí vận chuyển')),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='COD thu hộ')),
                ('weight_gram', models.IntegerField(blank=True, null=True, verbose_name='Khối lượng (gram)')),
                ('status', models.CharField(default='đang xử lý', max_length=20, verbose_name='Trạng thái')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi hàng')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippings.shippingpartner', verbose_name='Đơn vị vận chuyển')),
            ],
            options={
                'verbose_name': 'Thông tin vận chuyển',
                'verbose_name_plural': 'Danh sách vận chuyển',
            },
        ),
    ]
