# Generated by Django 5.2.9 on 2025-12-06 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Mã code')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khuyến mãi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị giảm')),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giảm tối đa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('usage_limit', models.IntegerField(blank=True, null=True, verbose_name='Giới hạn số lượt dùng')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lượt đã dùng')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Khuyến mãi',
                'verbose_name_plural': 'Khuyến mãi',
            },
        ),
        migrations.CreateModel(
            name='PromotionUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian sử dụng')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Khách hàng')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Đơn hàng')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion', verbose_name='Khuyến mãi')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng khuyến mãi',
                'verbose_name_plural': 'Lịch sử sử dụng khuyến mãi',
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mã sản phẩm')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion', verbose_name='Mã khuyến mãi')),
            ],
            options={
                'verbose_name': 'Sản phẩm áp dụng khuyến mãi',
                'verbose_name_plural': 'Sản phẩm áp dụng khuyến mãi',
                'unique_together': {('promotion', 'product_id')},
            },
        ),
    ]
