# Generated by Django 5.2.9 on 2025-12-29 16:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('orders', '0003_alter_order_total_amount'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian sử dụng')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Khách hàng')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Đơn hàng')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion', verbose_name='Khuyến mãi')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng khuyến mãi',
                'verbose_name_plural': 'Lịch sử sử dụng khuyến mãi',
            },
        ),
    ]
