# Generated by Django 5.2.9 on 2025-12-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '__first__'),
        ('promotions', '0002_promotionusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('start_date', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Sự kiện khuyến mãi',
                'verbose_name_plural': 'Sự kiện khuyến mãi',
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên quy tắc')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Giảm theo %'), ('FIXED', 'Giảm số tiền cố định')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị giảm')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='Số lượng tối thiểu')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá trị đơn tối thiểu')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.promotionevent', verbose_name='Sự kiện')),
                ('products', models.ManyToManyField(blank=True, related_name='promotion_rules', to='products.product', verbose_name='Sản phẩm áp dụng')),
            ],
            options={
                'verbose_name': 'Quy tắc khuyến mãi',
                'verbose_name_plural': 'Quy tắc khuyến mãi',
            },
        ),
    ]
