# Generated by Django 5.2.9 on 2025-12-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotionevent_promotionrule'),
        ('orders', '0004_remove_order_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionproduct',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='promotionusagelog',
            name='promotion',
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promotionproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='promotionusagelog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='promotionusagelog',
            name='order',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='PromotionProduct',
        ),
        migrations.DeleteModel(
            name='PromotionUsageLog',
        ),
    ]
