# Generated by Django 5.2.9 on 2025-12-15 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('products', '__first__'),
        ('promotions', '__first__'),
        ('stores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đơn')),
                ('status', models.CharField(default='đang chờ xử lý', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Phí vận chuyển')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='Mã địa chỉ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Khách hàng')),
                ('pickup_store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Cửa hàng nhận hàng')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.promotion', verbose_name='Mã khuyến mãi')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='Phương thức tt')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cổng thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(default='Đã thanh toán', max_length=20, verbose_name='Trạng thái')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order', verbose_name='Mã Đơn hàng')),
                ('shipping_method', models.CharField(max_length=255, verbose_name='Phương thức vận chuyển')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Phí vận chuyển')),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã vận đơn')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi hàng')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('status', models.CharField(default='đang chờ xử lý', max_length=20, verbose_name='Trạng thái vận chuyển')),
            ],
            options={
                'verbose_name': 'Thông tin vận chuyển',
                'verbose_name_plural': 'Thông tin vận chuyển',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Mã PTTT'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền giảm giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
