# Generated by Django 5.2.9 on 2025-12-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
