# Generated by Django 5.2.9 on 2025-12-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
