# Generated by Django 5.2.9 on 2025-12-14 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_payment_id'),
        ('stores', '0002_alter_storereservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Cửa hàng nhận hàng'),
        ),
    ]
