# Generated by Django 5.2.9 on 2025-12-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
    ]
