# Generated by Django 5.2.9 on 2026-01-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_promotion'),
        ('promotions', '0004_remove_promotionproduct_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.promotionevent', verbose_name='Sự kiện khuyến mãi'),
        ),
    ]
