# Generated by Django 5.2.9 on 2025-12-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Passwork_hash')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính')),
                ('status', models.CharField(default='Hoạt động', verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Mã khách hàng')),
            ],
            options={
                'unique_together': {('customer', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address_line', models.TextField(verbose_name='Đường')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã')),
                ('district', models.CharField(max_length=255, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=255, verbose_name='Thành Phố')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Mã khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gía')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cart', verbose_name='Mã giỏ hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mã sản phẩm')),
            ],
            options={
                'unique_together': {('cart', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm vào')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Mã khách hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mã sản phẩm')),
            ],
            options={
                'unique_together': {('customer', 'product_id')},
            },
        ),
    ]
