# Generated by Django 5.2.9 on 2025-12-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
